# Lab — Label Errors

This lab highlights data-centric AI techniques (using [confident learning](https://jair.org/index.php/jair/article/view/12125)) to improve the accuracy of an XGBoost classifier on a noisy dataset that has label errors.

The DCAI techniques demonstrated in this lab involve optimizing the dataset itself rather than altering the model's architecture or hyperparameters. As a result, it is possible to achieve further improvements in accuracy by fine-tuning the model in conjunction with the newly enhanced data, but that is not the focus of this lab.

In this lab, we will:

- Establish a baseline [XGBoost](https://xgboost.readthedocs.io/) model accuracy on the original data
- Automatically find mislabeled data points by:
    - Computing out-of-sample predicted probabilities
    - Estimating the number of label errors using confident learning
    - Ranking errors, using the number of label errors as a cutoff in identifying issues
- Remove the bad data
- Retrain the exact same XGBoost model to see the improvement in test accuracy

## Software installation

This lab relies on a couple PyPI packages. If you don't have them installed, run the following cell:

In [1]:
!pip install xgboost==1.7 scikit-learn pandas cleanlab

Reason for being yanked: <none given>
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.7 MB/s  0:00:02 eta 0:00:010m
  Attempting uninstall: xgboost
    Found existing installation: xgboost 3.0.5
    Uninstalling xgboost-3.0.5:
      Successfully uninstalled xgboost-3.0.5


## Setup and Data Processing

Let's take a look at the dataset used in this lab, a tabular dataset of student grades.

The data includes three exam scores (numerical features), a written note (categorical feature with missing values), and a (noisy) letter grade (categorical label). Our aim is to train a model to classify the grade for each student based on the other features.

In this dataset, 20% of the grade labels are actually incorrect (the `noisy_letter_grade` column). Synthetic noise was added to this dataset for the purpose of this lab. In this lab, we have access to the true letter grade each student should have received (the `letter_grade` column), which we use for evaluating both the underlying accuracy of model predictions and how well our approach detects which data are mislabeled. We are careful to only use these true grades for evaluation, not for model training.

In the real world, you don't have access to the true labels (you only observe the `noisy_letter_grade`, not the true `letter_grade`). So when evaluating models in the real world, you have to be careful to make sure that your test set is free of error (using methods like those covered in this lab, ideally combined with human review).

In [3]:
from xgboost import XGBClassifier
from sklearn import preprocessing
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

df = pd.read_csv("./student-grades.csv")
df.head()

stud_ID  exam_1  exam_2  exam_3                    notes letter_grade  \
0  f48f73      53      77      93                      NaN            C   
1  0bd4e7      81      64      80  great participation +10            B   
2  e1795d      74      88      97                      NaN            B   
3  cb9d7a      61      94      78                      NaN            C   
4  9acca4      48      90      91                      NaN            C   

  noisy_letter_grade  
0                  C  
1                  B  
2                  B  
3                  C  
4                  C

In [5]:
df_c = df.copy()
# Transform letter grades and notes to categorical numbers.
# Necessary for XGBoost.
df['letter_grade'] = preprocessing.LabelEncoder().fit_transform(df['letter_grade'])
df['noisy_letter_grade'] = preprocessing.LabelEncoder().fit_transform(df['noisy_letter_grade'])
df['notes'] = preprocessing.LabelEncoder().fit_transform(df["notes"])
df['notes'] = df['notes'].astype('category')
df.head()

stud_ID  exam_1  exam_2  exam_3 notes  letter_grade  noisy_letter_grade
0  f48f73      53      77      93     5             2                   2
1  0bd4e7      81      64      80     2             1                   1
2  e1795d      74      88      97     5             1                   1
3  cb9d7a      61      94      78     5             2                   2
4  9acca4      48      90      91     5             2                   2

# Get What We Need

To apply confident learning (the technique explained in today's lecture), we need to obtain [**out-of-sample** predicted probabilities](https://docs.cleanlab.ai/stable/tutorials/pred_probs_cross_val.html#out-of-sample-predicted-probabilities) for all of our data. To do this, we can use K-fold cross validation: for each fold, we will train on some subset of our data and get predictions on the rest of the data that was _not_ used for training.

We need to choose a model in order to do this. For this lab, we'll use [XGBoost](https://xgboost.readthedocs.io/), a library implementing gradient-boosted decision trees, a class of model commonly used for tabular data.

In [6]:
# Prepare training data (remove labels from the dataframe) and labels
data = df.drop(['stud_ID', 'letter_grade', 'noisy_letter_grade'], axis=1)
labels = df['noisy_letter_grade']

# XGBoost(experimental) supports categorical data.
# Here we use default hyperparameters for simplicity.
# Get out-of-sample predicted probabilities and check model accuracy.
model = XGBClassifier(tree_method="hist", enable_categorical=True)

# Exercise 1: getting out-of-sample predicted probabilities

Compute out-of-sample predicted probabilities for every data point. You can do this manually using for loops and multiple invocations of model training and prediction, or you can use scikit-learn's [cross_val_predict](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html) (if you're using this function, take a look at the documentations, and in particular, the `method=` keyword argument).

In [ ]:
# pred_probs should be a Nx5 matrix of out-of-sample predicted probabilities, with N = len(data)

from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
pred_probs = cross_val_predict(
    model, 
    data, 
    labels, 
    cv=cv, 
    method="predict_proba" # output with probabilities
)

print(pred_probs.shape) # check shape

(941, 5)


## Checking model accuracy on original data

Now that we have out-of-sample predicted probabilities, we can also check the model's (cross-val) accuracy on the original (noisy) data, so we'll have a baseline to compare our final results.

In [10]:
preds = np.argmax(pred_probs, axis=1)
acc_original = accuracy_score(preds, labels)
print(f"Accuracy with original data: {round(acc_original*100,1)}%")

Accuracy with original data: 68.0%


# Finding label issues automatically

We count label issues using confident learning. First, we need to compute class thresholds for the different classes.

# Exercise 2: computing class thresholds

Implement the Confident Learning algorithm for computing class thresholds for the 5 classes. You can refer to slide pp 30 from today's lecture or see equation 2 in [this paper](https://jair.org/index.php/jair/article/view/12125).

The class threshold for each class is the model's expected (average) self-confidence for each class. In other words, to compute the threshold for a particular class, you can average the predicted probability for that class, for all datapoints that are labeled with that particular class.

In [ ]:
def compute_class_thresholds(pred_probs: np.ndarray, labels: np.ndarray) -> np.ndarray:
    # YOUR CODE HERE
    n_classes = pred_probs.shape[1]
    thresholds = np.zeros(n_classes)
    for c in range(n_classes):
        # find out the indices of the samples in this class
        class_mask = (labels == c)
        if np.any(class_mask):
            # get average prediction probability for each class
            thresholds[c] = pred_probs[class_mask, c].mean()
        else:
            thresholds[c] = 0.0  # set 0.0 if no samples in this class
    return thresholds

In [12]:
# should be a numpy array of length 5
thresholds = compute_class_thresholds(pred_probs, labels.to_numpy())

In [13]:
thresholds

array([0.72652018, 0.62219751, 0.70514786, 0.49507931, 0.44896111])

# Exercise 3: constructing the confident joint

Next, we compute the confident joint, a matrix that counts the number of label errors for each noisy label $\tilde{y}$ and true label $y^*$. You can follow the algorithm that we walked through in slide pp 31 from today's lecture, or see equation 1 in [this paper](https://jair.org/index.php/jair/article/view/12125).

The confident joint C is a K x K matrix (with K = 5 for this dataset), where `C[i][j]` is an estimate of the count of the number of data points with noisy label `i` and true label `j`. From lecture, recall that we put a data point in bin `(i, j)` if its given label is `i`, and its predicted probability for class `j` is above the threshold for class `j` (`thresholds[j]`). Each data point should only go in a single bin; if a data point's predicted probability is above the class threshold for multiple classes, it goes in the bin for which it has the highest predicted probability.

In [ ]:
def compute_confident_joint(pred_probs: np.ndarray, labels: np.ndarray, thresholds: np.ndarray) -> np.ndarray:
    # YOUR CODE HERE
    n_classes = pred_probs.shape[1]
    C = np.zeros((n_classes, n_classes), dtype=int)

    for i in range(len(labels)):
        noisy_label = labels[i]              # noise label
        probs = pred_probs[i]                # predict label
        confident_classes = np.where(probs >= thresholds)[0]  # check whether the prediction class is above the threshold
        if len(confident_classes) == 0:
            continue  # pass if no number is beyond that
        # get the most class
        pred_class = confident_classes[np.argmax(probs[confident_classes])]
        C[noisy_label, pred_class] += 1

    return C

In [15]:
C = compute_confident_joint(pred_probs, labels.to_numpy(), thresholds)

In [16]:
C

array([[158,   6,  12,   6,  16],
       [  6, 142,   2,  44,   5],
       [  2,   2, 102,   9,   8],
       [  0,  39,   0,  78,   8],
       [ 22,  15,  14,  12,  69]])

# Exercise 4: count the number of label issues

Now that we have the confident joint C, we can count the estimated number of label issues in our dataset. Recall that this is the sum of the off-diagonal entries (the cases where we estimate that a label has been flipped).

In [18]:
num_label_issues = C.sum() - np.trace(C)
num_label_issues

228

In [19]:
print('Estimated noise rate: {:.1f}%'.format(100*num_label_issues / pred_probs.shape[0]))

Estimated noise rate: 24.2%


# Exercise 5: filter out label issues

In this lab, our approach to identifying issues is to rank the data points by a score ("self-confidence", the model's predicted probability for a data point's given label) and then take the top `num_label_issues` of those.

First, we want to compute the model's _self-confidence_ for each data point. For a data point `i`, that is `pred_probs[i, labels[i]]`.

In [ ]:
# this should be a numpy array of length 941 of probabilities
self_confidences = pred_probs[np.arange(len(labels)), labels]
print(self_confidences.shape)  
print(self_confidences[:5])

(941,)
[0.9542228  0.91627544 0.9714257  0.7182924  0.5194559 ]


Next, we rank the _indices_ of the data points by the self-confidence.

In [24]:
# this should be a numpy array of length 941 of integer indices
ranked_indices = np.argsort(self_confidences)
ranked_indices

array([637, 689, 673, 709, 629, 291, 760, 139,  36, 264,  23, 174,  83,
       284,  71, 918, 421, 409, 680,  18, 900, 404, 763, 910, 159, 619,
       774, 318, 502, 660, 173, 303, 795, 811, 161, 744,  27, 496, 545,
       864, 190, 184, 886, 437, 457, 498, 179, 765, 169, 552, 815, 875,
       885, 230, 781,  57, 158, 882, 539, 727, 144, 238, 865, 550, 702,
        69, 491, 210, 253, 476, 836, 548, 143, 562, 931, 872, 513, 595,
       382, 641, 233, 937, 589,  11, 567, 911, 301, 212,  56, 666, 928,
        75, 225, 504, 410, 854, 827, 130, 378, 259, 285, 653, 105, 560,
       431, 848, 468, 579, 424, 367, 840, 388, 193, 800, 322, 150, 631,
       813, 154,  45, 117, 849, 129, 826, 936, 705, 346, 853, 651, 561,
       506, 809,  73,  65, 603,  32,  62, 484, 799, 122, 841, 440, 723,
       320, 430, 874, 917, 208, 325, 383,  49, 814, 648, 452, 271, 135,
       710, 528, 679, 172,  17, 324, 847, 824, 517,  37, 166, 909, 227,
       940, 199, 584, 219, 456,  14, 828, 272, 650, 332, 934, 78

Finally, let's compute the indices of label issues as the top `num_label_issues` items in the `ranked_indices`.

In [26]:
issue_idx = ranked_indices[:num_label_issues]
issue_idx

array([637, 689, 673, 709, 629, 291, 760, 139,  36, 264,  23, 174,  83,
       284,  71, 918, 421, 409, 680,  18, 900, 404, 763, 910, 159, 619,
       774, 318, 502, 660, 173, 303, 795, 811, 161, 744,  27, 496, 545,
       864, 190, 184, 886, 437, 457, 498, 179, 765, 169, 552, 815, 875,
       885, 230, 781,  57, 158, 882, 539, 727, 144, 238, 865, 550, 702,
        69, 491, 210, 253, 476, 836, 548, 143, 562, 931, 872, 513, 595,
       382, 641, 233, 937, 589,  11, 567, 911, 301, 212,  56, 666, 928,
        75, 225, 504, 410, 854, 827, 130, 378, 259, 285, 653, 105, 560,
       431, 848, 468, 579, 424, 367, 840, 388, 193, 800, 322, 150, 631,
       813, 154,  45, 117, 849, 129, 826, 936, 705, 346, 853, 651, 561,
       506, 809,  73,  65, 603,  32,  62, 484, 799, 122, 841, 440, 723,
       320, 430, 874, 917, 208, 325, 383,  49, 814, 648, 452, 271, 135,
       710, 528, 679, 172,  17, 324, 847, 824, 517,  37, 166, 909, 227,
       940, 199, 584, 219, 456,  14, 828, 272, 650, 332, 934, 78

Let's look at a couple of the highest-ranked data points (most likely to be label issues):

In [27]:
df_c.iloc[ranked_indices[:5]]

stud_ID  exam_1  exam_2  exam_3 notes  letter_grade  noisy_letter_grade
637  77c9c5       0      79      65     0             4                   0
689  b0306d      77      51      70     5             3                   1
673  64c2db      96      76      85     5             1                   4
709  3dd1e5      64      70      86     5             2                   4
629  942d65      80      76      96     3             2                   0

# How'd We Do?

Let's go a step further and see how we did at automatically identifying which data points are mislabeled. If we take the intersection of the labels errors identified by Confident Learning and the true label errors, we see that our approach was able to identify 75% of the label errors correctly (based on predictions from a model that is only 67% accurate). 

In [33]:
# Computing percentage of true errors identified. 
true_error_idx = df[df.letter_grade != df.noisy_letter_grade].index.values
cl_acc = len(set(true_error_idx).intersection(set(issue_idx)))/len(true_error_idx)
print(f"Percentage of errors found: {round(cl_acc*100,1)}%")

Percentage of errors found: 81.4%


# Train a More Robust Model

Now that we have the indices of potential label errors within our data, let's remove them from our data, retrain our model, and see what improvement we can gain.

Keep in mind that our baseline model from above, trained on the original data using the `noisy_letter_grade` as the prediction label, achieved a cross-validation accuracy of 67%.

Let's use a very simple method to handle these label errors and just drop them entirely from the data and retrain our exact same `XGBClassifier`. In a real-world application, a better approach might be to have humans review the issues and _correct_ the labels rather than dropping the data points.

In [34]:
# Remove the label errors found by Confident Learning
data = df.drop(issue_idx)
clean_labels = data['noisy_letter_grade']
data = data.drop(['stud_ID', 'letter_grade', 'noisy_letter_grade'], axis=1)

# Train a more robust classifier with less erroneous data
model = XGBClassifier(tree_method="hist", enable_categorical=True)
clean_pred_probs = cross_val_predict(model, data, clean_labels, method='predict_proba')
clean_preds = np.argmax(clean_pred_probs, axis=1)

acc_clean = accuracy_score(clean_preds, clean_labels)
print(f"Accuracy with original data: {round(acc_original*100, 1)}%")
print(f"Accuracy with errors found by Confident Learning removed: {round(acc_clean*100, 1)}%")

# Compute reduction in error.
err = ((1-acc_original)-(1-acc_clean))/(1-acc_original)
print(f"Reduction in error: {round(err*100,1)}%")

Accuracy with original data: 68.0%
Accuracy with errors found by Confident Learning removed: 88.9%
Reduction in error: 65.4%


After removing the suspected label issues, our model's new cross-validation accuracy is now 90%, which means we **reduced the error-rate of the model by 70%** (the original model had 67% accuracy). 

**Note: throughout this entire process we never changed any code related to model architecture/hyperparameters, training, or data preprocessing!  This improvement is strictly coming from increasing the quality of our data which leaves additional room for additional optimizations on the modeling side.**

# Conclusion

For the student grades dataset, we found that simply dropping identified label errors and retraining the model resulted in a 70% reduction in prediction error on our classification problem (with accuracy improving from 67% to 90%).

An implementation of the Confident Learning algorithm (and much more) is available in the [cleanlab](https://github.com/cleanlab/cleanlab) library on GitHub. This is how today's lab assignment can be done in a single line of code with Cleanlab:

In [37]:
import cleanlab

cl_issue_idx = cleanlab.filter.find_label_issues(labels, pred_probs, return_indices_ranked_by='self_confidence')
len(cl_issue_idx)

258

In [36]:
df_c.iloc[cl_issue_idx[:5]]

stud_ID  exam_1  exam_2  exam_3 notes  letter_grade  noisy_letter_grade
637  77c9c5       0      79      65     0             4                   0
689  b0306d      77      51      70     5             3                   1
673  64c2db      96      76      85     5             1                   4
709  3dd1e5      64      70      86     5             2                   4
629  942d65      80      76      96     3             2                   0

_Advanced topic_: you might notice that the above `cl_issue_idx` differs in length (by a little bit) from our `issue_idx`. The reason for this is that we implemented a slightly simplified version of the algorithm in this lab. We skipped a calibration step after computing the confident joint that makes the confident joint have the true noisy prior $p(labels)$ (summed over columns for each row) and also add up to the total number of examples. If you're interested in the details of this, see equation 3 and the subsequent explanation in the [paper](https://jair.org/index.php/jair/article/view/12125).